apiVersion: v1
kind: Service
metadata:
  name: f5-hello-world-service-clusterip
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: f5-hello-world-web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: f5-hello-world-web
